openfga/sample-stores

.github/CODEOWNERS
.github/workflows/semgrep.yaml
README.md

This adds:
- Semgrep CI
- CODEOWNERS file
- Discord & Twitter badges to the readme

chore: add semgrep, codeowners & repo badges

---

stores/custom-roles/README.md
stores/custom-roles/assertions.json
stores/custom-roles/authorization-model.json
stores/custom-roles/tuples.json
stores/entitlements/README.md
stores/entitlements/assertions.json
stores/entitlements/authorization-model.json
stores/entitlements/tuples.json
stores/gdrive/README.md
stores/gdrive/assertions.json
stores/gdrive/authorization-model.json
stores/gdrive/tuples.json
stores/github/README.md
stores/github/assertions.json
stores/github/authorization-model.json
stores/github/tuples.json
stores/iot/README.md
stores/iot/assertions.json
stores/iot/authorization-model.json
stores/iot/tuples.json
stores/slack/README.md
stores/slack/assertions.json
stores/slack/authorization-model.json
stores/slack/tuples.json

feat: add user type

---

stores/github/README.md

Fix some simple typos in the README.md of the github store sample

fix typos in github store README

---

stores/expenses/README.md
stores/expenses/assertions.json
stores/expenses/authorization-model.json

fix: updated expenses to no longer have a now invalid syntax

---

stores/custom-roles/README.md
stores/custom-roles/authorization-model.json
stores/entitlements/README.md
stores/entitlements/authorization-model.json
stores/expenses/README.md
stores/expenses/authorization-model.json
stores/gdrive/README.md
stores/gdrive/authorization-model.json
stores/gdrive/tuples.json
stores/github/README.md
stores/github/authorization-model.json
stores/iot/README.md
stores/iot/authorization-model.json
stores/slack/README.md
stores/slack/authorization-model.json

feat: add type restrictions to json syntax

---

stores/advanced-entitlements/README.md
stores/advanced-entitlements/store.fga.yaml
stores/banking/README.md
stores/banking/store.fga.yaml
stores/groups-resource-attributes/README.md
stores/groups-resource-attributes/store.fga.yaml
stores/ip-based-access/README.md
stores/ip-based-access/store.fga.yaml
stores/temporal-access/README.md
stores/temporal-access/store.fga.yaml

Adding samples for conditional relationship tuples.
- [ X] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

feat: adding samples for conditional tuples

---

stores/condition-data-types/README.md
stores/condition-data-types/store.fga.yaml
stores/temporal-access/store.fga.yaml

- Added example showcasing the different data types and expressions
- Added ListObjects example in the IP Based Access store
-

New example + fixes for ABAC use cases

---

.github/workflows/main.yaml
stores/superadmin/README.md
stores/superadmin/store.fga.yaml

Added example to describe how to model access to a super admin user, a super admin app, and a helpdesk user.

Added super admin example

---

stores/banking/store.fga.yaml

Minor tweaks in the Banking example

chore: improve banking example

---

README.md

chore: added canonical/lxd model

---

README.md
stores/gdrive/store.fga.yaml
stores/github/store.fga.yaml

Add list_users examples & update readme

---

README.md

chore: added grafana's model

---

README.md

Added link to sourcegraph model

Added link to sourcegraph model

---

README.md

chore: link to klothoplatform/infracopilot model

---

README.md
stores/advanced-entitlements/README.md
stores/banking/README.md
stores/condition-data-types/README.md
stores/custom-roles/store.fga.yaml
stores/developer-portal/README.md
stores/developer-portal/store.fga.yaml
stores/entitlements/store.fga.yaml
stores/expenses/store.fga.yaml
stores/gdrive/store.fga.yaml
stores/github/store.fga.yaml
stores/groups-resource-attributes/README.md
stores/iot/store.fga.yaml
stores/ip-based-access/README.md
stores/ip-based-access/store.fga.yaml
stores/modular/README.md
stores/modular/wiki.fga
stores/slack/store.fga.yaml
stores/superadmin/README.md
stores/superadmin/store.fga.yaml
stores/temporal-access/README.md
stores/temporal-access/store.fga.yaml

chore: improved scenarios descriptions, added listusers/objects tests

---

.vscode/settings.json
README.md

chore: added new internal/external examples + dictionary entries

---

README.md

Added Lakekeeper's Model
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)

chore(docs): add Lakekeeper's Model to README

---

stores/condition-data-types/store.fga.yaml

chore: clarified duration syntax

---

README.md

chore: update content in README

---

README.md

Updated model location for Lakekeeper

chore(docs): update lakekeeper model location

---

stores/modular/README.md
stores/modular/core-tuples.yaml
stores/modular/core.fga.yaml
stores/modular/issue-tracker.fga.yaml
stores/modular/wiki.fga.yaml

chore:  change tests so they are organized per module

---

stores/role-bindings/README.md
stores/role-bindings/store.fga.yaml

Add role-bindings example

---

.github/workflows/main.yaml

Added additional sample stores to test

Added additional sample stores to test
